// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateapplicationsaddclickcount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateapplicationsaddclickcount));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081702539_update-applications-add-click-count"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
