// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createupdatedtablesapplicationsapiKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createupdatedtablesapplicationsapiKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201904162002023_create-updated-tables-applications-apiKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
